import os

import pandas as pd
from rdkit import Chem

DOCKING_RESULTS = "docking/results/standardized_affinities.csv"
POSE_DIR = "docking/results/standardized"
OUTPUT_DIR = "docking/results/fixed"

df_all = pd.read_csv(DOCKING_RESULTS)
df_all["affinity"] = pd.to_numeric(df_all["affinity"], errors="coerce")
df_all = df_all[df_all["status"].isin(["ok", "existing"])].dropna(subset=["affinity"])
df_all = df_all.sort_values("affinity").reset_index(drop=True)
top_5 = df_all.head(5)["ligand_id"].tolist()
print(f"Standardized Top 5: {top_5}\n")

if len(top_5) != 5:
    raise RuntimeError(f"Expected 5 Top hits, found {len(top_5)}")

os.makedirs(OUTPUT_DIR, exist_ok=True)


def remove_all_hydrogens(mol):
    """Remove every H atom, including isolated/malformed H atoms."""
    editable = Chem.RWMol(mol)
    h_indices = [
        atom.GetIdx()
        for atom in editable.GetAtoms()
        if atom.GetSymbol() == "H"
    ]
    for idx in sorted(h_indices, reverse=True):
        editable.RemoveAtom(idx)
    return editable.GetMol()


def parse_pdbqt_heavy_atoms(pdbqt_path):
    """
    Read docked heavy-atom coordinates directly from PDBQT.

    This avoids Open Babel/RDKit reordering of atoms and keeps the atom order
    generated by the docking/preparation pipeline.
    """
    atoms = []
    with open(pdbqt_path, "r", encoding="utf-8") as handle:
        for line in handle:
            if not line.startswith(("ATOM", "HETATM")):
                continue

            atom_name = line[12:16].strip()
            try:
                x = float(line[30:38])
                y = float(line[38:46])
                z = float(line[46:54])
            except ValueError:
                continue

            element = line[77:79].strip()
            if not element:
                element = atom_name[:1].upper()

            if element.upper() == "H":
                continue

            atoms.append(
                {
                    "name": atom_name,
                    "element": element.capitalize(),
                    "x": x,
                    "y": y,
                    "z": z,
                }
            )

    return atoms


def build_from_template_and_pose(pdbqt_path, template_sdf, output_sdf):
    """
    Keep chemical connectivity/bond orders from the trusted template and
    transfer heavy-atom coordinates from the standardized PDBQT pose.
    """
    try:
        template = Chem.MolFromMolFile(
            template_sdf,
            removeHs=False,
            sanitize=False,
        )
        if template is None:
            return False, "Cannot read template"

        template_noH = remove_all_hydrogens(template)
        pose_atoms = parse_pdbqt_heavy_atoms(pdbqt_path)

        if len(pose_atoms) != template_noH.GetNumAtoms():
            return (
                False,
                f"Heavy-atom mismatch ({len(pose_atoms)} vs "
                f"{template_noH.GetNumAtoms()})",
            )

        template_symbols = [
            atom.GetSymbol().capitalize()
            for atom in template_noH.GetAtoms()
        ]
        pose_symbols = [atom["element"] for atom in pose_atoms]

        if template_symbols != pose_symbols:
            return (
                False,
                "Heavy-atom element/order mismatch",
            )

        final_mol = Chem.Mol(template_noH)
        final_mol.RemoveAllConformers()

        conf = Chem.Conformer(template_noH.GetNumAtoms())
        for idx, atom in enumerate(pose_atoms):
            conf.SetAtomPosition(
                idx,
                (atom["x"], atom["y"], atom["z"]),
            )

        final_mol.AddConformer(conf, assignId=True)
        final_mol = Chem.AddHs(final_mol, addCoords=True)
        Chem.SanitizeMol(final_mol)

        writer = Chem.SDWriter(output_sdf)
        writer.write(final_mol)
        writer.close()

        return True, "template + PDBQT coordinates"

    except Exception as exc:
        return False, f"{type(exc).__name__}: {exc}"


success, failed = [], []
print("Preparing standardized Top 5 for ProLIF...\n")

for lid in top_5:
    pdbqt = f"{POSE_DIR}/{lid}_out.pdbqt"
    output = f"{OUTPUT_DIR}/{lid}_fixed.sd"

    if not os.path.exists(pdbqt):
        print(f"  FAIL {lid:5s} — standardized pose not found")
        failed.append(lid)
        continue

    template = "pdb/ligand.sd" if lid == "13U" else f"ligands/{lid}.sdf"

    ok, method = build_from_template_and_pose(
        pdbqt, template, output
    )

    if ok:
        print(f"  OK   {lid:5s} via {method}")
        success.append(lid)
    else:
        print(f"  FAIL {lid:5s} — {method}")
        failed.append(lid)

print(f"\n{'=' * 60}")
print(f"  Success: {len(success)}/{len(top_5)}")
print(f"  Failed:  {len(failed)}/{len(top_5)}")
print(f"{'=' * 60}")

if failed:
    print(f"\nFailed ligands: {failed}")
